Update index.html
htmlacademy-htmlcss/1905411-sedona-34 pull request #2
Opened 2022-05-25 18:44 UTC by Hodyreves

разметка страницы в файле index.html

2022-05-26 06:47 UTC, mkolotovich requested changes
По заданию необходимо выполнить разметку всех страниц, а вы разметили только главную.

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <a class="navigation-link" href="main.html">Главная</a>
Ссылка ведет на несуществующую страницу. Здесь вообще не нужег атрибут href так как это ссылка на текущую страницу

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <a calss="navigation-link" href="about-sedona.html">О Седоне</a>
В задании указано - Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`.

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <a class="navigation-link" href="hotels.html">Гостиницы</a>
По заданию необходимо выполнить разметку страниц в файлах index.html и catalog.html, т.е. здесь должна быть ссылка на страницу catalog.html

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +        <!--индикатор текущей страницы в макете. Не понятно -->
Это нужно повесить дополнительный класс на текущую страницу, например active

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +              <span class="visuallu-hidden">
По заданию - Для скрытых элементов используйте класс class="visually-hidden", у вас опечатка в имени класса

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +              </span>
Этот элемент отображается на странице, поэтому нет смысла задавать ему класс visuallu-hidden

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +    <main class="main-index"></main>
тег main должен закрывать перед футером

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +      <h1 class="visuallu-hidden">Добро пожаловать в великолепную Седону, потому что Гранд-каньон - отстой</h1>
Пропустили изображение welcome to the georgeous sedona

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +      <h2 class="city-intro">Седона — небольшой городок в Аризоне,<br>
тег br используйте только тогда когда невозможно выполнить перенос как на макете с помощью стилей, здесь можно сделать перенос стилями, так что br здесь не нужен

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +      <p advantages-intro>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
пропустили атрибут class

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +        <h2 class="visuallu-hidden">Преимущества</h2>
Для скрытых элементов используйте класс class="visually-hidden"

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +                <p class="advantages-description">Рекомендуем пожить<br>в настоящем мотеле,<br>всё как в кино!</p>
теги br здесь лишние

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +                <p class="advantages-description">Всегда заказывайте<br>топовый фирменный бургер,<br>вы не разочаруетесь!</p>
удалите второй br, он избыточен

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +                <p class="advantages-description">Не только китайского,<br>но и настоящего местного<br>производства!</p>
удалите второй br, он избыточен

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <h3 class="advatages-title">Там есть<br>мост дьявола</h3>
удалите br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <p class="advantages-description">Да, по нему можно пройти!<br> Если вы осмелитесь,<br> разумеется</p>
удалите теги br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <h3 class="advatages-title">Небольшая<br>площадь</h3>
удалите тег br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <p class="advantages-description">Все достопримечательности<br>находятся очень близко</p>
удалите тег br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <h3 class="advatages-title">Красивая<br>дорога</h3>
удалите тег br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <p class="advantages-description">Ехать в Седону из Лас-Вегаса<br> совсем не скучно!</p>
удалите тег br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <h3 class="advatages-title">Мало<br>туристов</h3>
удалите тег br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +            <p class="advantages-description">Большинство едет в Гранд<br> Каньон и толпится там</p>
удалите тег br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +        <p class="subscription-description">Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
удалите тег br

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +      <p></p>
Зачем этот пустой параграф?

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +          <a class="button" href="https://www.youtube.com/user/htmlacademy">
У ссылок пропущен закрывающий тег

2022-05-26 06:47 UTC, mkolotovich commented on index.html
> +      <a class="button-htmlacademy-link" href="https://htmlacademy.ru">html academy</a>
здесь вместо текста внутри ссылки необходимо использовать изображение

2022-05-26 14:31 UTC, mkolotovich commented on index.html
> +            <a calss="navigation-link" href="about-sedona.html">О Седоне</a>
ну текст, то внутри ссылки необходимо было оставить то)

2022-05-26 14:37 UTC, mkolotovich commented on index.html
> +                <p class="advantages-description">Всегда заказывайте<br>топовый фирменный бургер,<br>вы не разочаруетесь!</p>
первый br верните, он здесь нужен

2022-05-26 14:38 UTC, mkolotovich commented on index.html
> +                <p class="advantages-description">Не только китайского,<br>но и настоящего местного<br>производства!</p>
первый br верните, он здесь нужен

2022-05-26 14:57 UTC, mkolotovich requested changes
исправьте комментарии

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +                <a class="navigation-link">Главная</a>
По заданию - Если страница существует в макете, то на неё должна вести соответствующая ссылка, например, `<a href="catalog.html">`.

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +                <a calss="navigation-link" href="#"></a> <!--О Седоне ссылка на страницу-->
Добавьте текст - О Седоне внутрь ссылки

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +                <a class="navigation-link navigation-link-current" href="catalog.html">Гостиницы</a>
страница ссылается сама на себе, здесь атрибут href не нужен

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +                <a calss="navigation-link" href="#">
опечатка в имена атрибута calss, должен быть class

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +                  </span>
эта обёртка лишняя, удалите её

2022-05-26 14:57 UTC, mkolotovich commented on index.html
>                </span>
эта обёртка лишняя, удалите её

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +                  <label for="" class="control">
если input лежит внутри label то атрибут for не нужен у label

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +                  <label for="" class="control">
если input лежит внутри label то атрибут for не нужен у label

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +
не размечен блок Стоимость, ₽:

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +            <button class="button" type="submit">Сбросить</button>
у кнопки сброса должен быть type="reset"

2022-05-26 14:57 UTC, mkolotovich commented on catalog.html
> +
пропущен текст - Найдено гостиниц: 38

2022-05-27 06:25 UTC, mkolotovich requested changes
Исправьте не схлопнутые комментарии с прошлой проверки плюс добавились новые

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +              <b class="hotel-card-price">От 4000 ₽</b>
зачем вы этот текст оборачиваете в `<b>` он же не жирный на макете? используйте просто `<span>  `

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +                <span class="star">*</span>
звезды это изображения поэтому используйте тег img и их здесь на макете 4, а не 5)

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +                <b class="hotel-card-text">Рейтинг: 8,5</b>
в макете этот текст не жирный, так что нет смысла использовать здесь тег `<b>`.  используйте просто `<span>`. Вынесите из дива этот элемент, чтобы удобнее было делать сетку

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +            </li>
остальные элементы списка разметьте по примеру первого

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +          </li>
этого в макете нет. Не нужно верстать того, чего нет в макете)

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +            <a class="pagination-link" href="#">5</a>
этого в макете нет, зато есть элемент - ...

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +              <span class="visually-hidden">Следующая страница</span>
этого тоже в макете нет, зато есть - 10

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +        <button class="button pagination-show-more" type="button">Показать ещё</button>
Откуда вы это берете? Необходимо перенести вёрстку с макета, а вы откуда берете эти элементы?

2022-05-27 06:25 UTC, mkolotovich commented on catalog.html
> +        <p class="subscription-description">Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
уберите тег <br> он здесь лишний

2022-05-27 07:17 UTC, Hodyreves commented on catalog.html
> +                <a calss="navigation-link" href="#">
калас

2022-05-27 08:22 UTC, Hodyreves commented on catalog.html
> +                <a calss="navigation-link" href="#">
исправил в idex и catalog

2022-05-27 08:26 UTC, Hodyreves commented on index.html
>                </span>
сделал

2022-05-27 10:43 UTC, mkolotovich commented on catalog.html
> +
для словосочетания Стоимость, ₽ лучше исползовать тег b или strong. Также не размечены поля ввода стоимости от и до

2022-05-27 10:48 UTC, mkolotovich requested changes
Исправьте не схлопнутые комментарии с прошлых проверок

2022-05-27 13:00 UTC, mkolotovich requested changes
Исправьте 3 не схлопнутых комментария с прошлых проверок

2022-05-27 13:00 UTC, mkolotovich commented on catalog.html
> +                  <input class="price"  placeholder="9000 от" type="text" name="max-price" value="9000 от">
когда указано значение в атрибуте value, placeholder не отображается.

2022-05-28 12:28 UTC, Hodyreves commented on index.html
> +                <p class="advantages-description">Всегда заказывайте<br>топовый фирменный бургер,<br>вы не разочаруетесь!</p>
Исправил br

2022-05-28 12:30 UTC, Hodyreves commented on index.html
> +                <p class="advantages-description">Не только китайского,<br>но и настоящего местного<br>производства!</p>
Исправил br

2022-05-28 19:52 UTC, mkolotovich commented on index.html
> +                <p class="advantages-description">Всегда заказывайте<br>топовый фирменный бургер,<br>вы не разочаруетесь!</p>
исправили, но не так(. Первый br нужно было оставить, а второй убрать.

2022-05-28 19:53 UTC, mkolotovich requested changes
Исправьте один комментарий и я приму ваш ПР)

2022-05-28 20:38 UTC, Hodyreves commented on index.html
> +                <p class="advantages-description">Всегда заказывайте<br>топовый фирменный бургер,<br>вы не разочаруетесь!</p>
Сделал

2022-05-28 21:10 UTC, Hodyreves commented
> Исправьте один не схлопнутый комментарий и я приму ваш ПР)

Исправил

2022-05-29 08:36 UTC, merged